### PR TITLE
Delete apps release and Docker image build workflows

### PR DESCRIPTION
**Pull request by arunsathiya**
They are not used in this fork project anyway.

Signed-off-by: Arun <arun@arun.blog>

### CODE REVIEW

**Comment by sharunkumar** [comment]
problem with this is, it will create merge conflict issues when merging from upstream if they update it in any way, thus making any auto-mergings fail

**Review by sharunkumar — COMMENTED** [review]
problem with this is, it will create merge conflict issues when merging from upstream if they update it in any way, thus making any auto-mergings fail

**Comment by arunsathiya** [comment]
>If your local branch had unique commits, you may need to resolve conflicts. For more information, see "[Addressing merge conflicts](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts)."

Based on this part of [the docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork), it does seem that this will result in conflicts.

I see that your fork is 100+ commits ahead. So, you are bound to run into merge conflicts when syncing, right? With that understanding, are you manually fixing them at the moment?

**Comment by sharunkumar** [comment]
@arunsathiya is there any way of disabling certain workflows? in that case, we don't have to delete these
also I think this PR should go hand in hand with #1 

basically I want to enable #1 but disable these without deleting the files

**Comment by sharunkumar** [comment]
@arunsathiya running `gh workflow` gives the following output:
```
gh workflow 
List, view, and run workflows in GitHub Actions.

USAGE
  gh workflow <command> [flags]

AVAILABLE COMMANDS
  disable:     Disable a workflow
  enable:      Enable a workflow
  list:        List workflows
  run:         Run a workflow by creating a workflow_dispatch event
  view:        View the summary of a workflow

FLAGS
  -R, --repo [HOST/]OWNER/REPO   Select another repository using the [HOST/]OWNER/REPO format

INHERITED FLAGS
  --help   Show help for command

LEARN MORE
  Use 'gh <command> <subcommand> --help' for more information about a command.
  Read the manual at https://cli.github.com/manual
```

can this be used to disable workflows rather than deleting the yml files?

**Comment by sharunkumar** [comment]
Just realized that you can do this with the UI too:

image

closing this as I've disabled the other workflows:

```
gh workflow list -a
NAME                           STATE              
Build Apps and Create Release  disabled_manually  
ci                             disabled_manually  
build & push docker container  disabled_manually  
Fly Deploy                     active             
```

**Pull request closed without merging**
